#!/bin/bash

set -e  # Exit immediately if a command fails


echo "Starting Minikube cluster..."
minikube start

echo "Verifying cluster info..."
kubectl cluster-info

echo "Retrieving available pods (all namespaces)..."
kubectl get pods --all-namespaces
